# Generated by Django 3.1.3 on 2020-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='shortCode',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
