# Generated by Django 3.1.3 on 2020-11-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_hospital_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='shortCode',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
